web:
  image: nginx:1.11-alpine
  links:
    - php
  ports:
    - "8080:80"
  volumes:
    - ./nginx.conf:/etc/nginx/conf.d/default.conf
  volumes_from:
    - htdocs
php:
  build: php-7.0-fpm-custom
  links:
    - db
  volumes_from:
    - htdocs
db:
  image: mariadb:10.1
  environment:
    MYSQL_ROOT_PASSWORD: change_this
htdocs:
  image: busybox
  stdin_open: true
  volumes:
    - htdocs:/var/www/html
